#!/bin/bash

min_width="${1:-1915}"

echo '{"version":1}'
echo '['
stdbuf -i0 -o0 jq -caR '[{"name":"output","min_width":'"$min_width"',"full_text":.}]' | stdbuf -i0 -o0 awk '{printf("%s%s\n", (NR==1?"":","), $0);}'
