#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# based on https://stackoverflow.com/questions/17781558/xmms2-track-change-detection-for-pynotify

from __future__ import print_function
from __future__ import unicode_literals

import xmmsclient

# This is broken, see https://bugs.launchpad.net/ubuntu/+source/xmms2/+bug/1945885
#from xmmsclient.glib import GLibConnector
# Until it gets fixed, this is an inlined version of /usr/lib/python3/dist-packages/xmmsclient/glib.py
# with a fixed import line.
# See https://stackoverflow.com/questions/37323567/install-gobject-module/37324160#37324160
# See https://github.com/mrichar1/clipster/issues/93
from gi.repository.GLib import io_add_watch, IO_OUT, IO_IN, source_remove
class GLibConnector:
	def __init__(self, xmms):
		self.in_id = None
		self.out_id = None
		self.reconnect(xmms)

	def need_out(self, i):
		if self.xmms.want_ioout() and self.out_id is None:
			self.out_id = io_add_watch(self.xmms.get_fd(), IO_OUT, self.handle_out)

	def handle_in(self, source, cond):
		if cond == IO_IN:
			return self.xmms.ioin()

		return True

	def handle_out(self, source, cond):
		if cond == IO_OUT and self.xmms.want_ioout():
			self.xmms.ioout()
		if not self.xmms.want_ioout():
			self.out_id = None

		return not self.out_id is None

	def reconnect(self, xmms=None):
		self.disconnect()
		if not xmms is None:
			self.xmms = xmms
		self.xmms.set_need_out_fun(self.need_out)
		self.in_id = io_add_watch(self.xmms.get_fd(), IO_IN, self.handle_in)
		self.out_id = None

	def disconnect(self):
		if not self.in_id is None:
			source_remove(self.in_id)
			self.in_id = None
		if not self.out_id is None:
			source_remove(self.out_id)
			self.out_id = None

import os
import sys
from gi.repository import GLib as gobject
import json
import yaml
import copy
import io
import sys
import string


class MyFormatter(string.Formatter):
    def get_field(self, field, *args, **kwargs):
        try:
            return super(MyFormatter, self).get_field(field, *args, **kwargs)
        except (KeyError, IndexError) as err:
            return ('¿{}?'.format(err), field)
        except TypeError as err:
            return ('?', field)

    def get_value(self, key, *args, **kwargs):
        try:
            return super(MyFormatter, self).get_value(key, *args, **kwargs)
        except (KeyError, IndexError) as err:
            return '¿{}?'.format(err)
        except TypeError as err:
            return '?'

formatter = MyFormatter()

def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)

def format_timedelta(secs):
    seconds = int(secs / 1000)

    secs_in_a_hour = 3600
    secs_in_a_min = 60

    hours, seconds = divmod(seconds, secs_in_a_hour)
    minutes, seconds = divmod(seconds, secs_in_a_min)

    time_fmt = "{seconds:02d}".format(**locals())

    if hours > 0:
        time_fmt = "{minutes:02d}:{time_fmt}".format(**locals())
        time_fmt = "{hours:d}:{time_fmt}".format(**locals())
    else:
        time_fmt = "{minutes:d}:{time_fmt}".format(**locals())
    return time_fmt


default_config = {
    'line': '{playback_status_icon} ({playlist_current_position}/{playlist_num_entries}) {playback_current_info[title]} - {playback_current_info[album]} - {playback_current_info[artist]}',
    #'line': '{playback_status_icon} [{playlist_current_position}/{playlist_num_entries}] {playback_current_info[tracknr]}. {playback_current_info[title]} ({playback_current_info[duration_formatted]}) - {playback_current_info[album]} ({playback_current_info[date]}) - {playback_current_info[artist]}',

    'playback_status_icons': {
        'stop': '[⏹]',
        #'play': '[▶]',  # this play icon doesn't have the same width as stop and pause (in non-monospaced fonts)
        'play': '[⏵]',  # this play icon does
        'pause': '[⏸]',

        #'stop': '⏹️',
        #'play': '▶️',
        #'pause': '⏸️',
    },
}
#eprint(repr(default_config))

info = {
    'config': copy.deepcopy(default_config),
    'config_fname': os.environ['HOME'] + '/.xmms2-tail.yaml',
    'config_fname_mtime': 0,
}

# 0 = stopped, 1 = playing, 2 = paused
playback_status_icon_name = [ 'stop', 'play', 'pause' ]

def update(name, result):
    if not result.is_error():
        global info

        value = result.value()
        #eprint(name, repr(value))
        info[name] = value

        try:
            new_mtime = os.path.getmtime(info['config_fname'])
            if new_mtime != info['config_fname_mtime']:
                #eprint("xmms2-tail: reading config file")
                with io.open(info['config_fname'], mode='r', encoding='utf-8') as stream:
                    # FIXME: merge the config file into default_config, and use that.
                    # Probably not - there's no clean, easy, idiomatic way to do that (even though there should be).
                    info['config'] = yaml.safe_load(stream)
                    info['config']['line'] = info['config']['line'].decode('utf-8')
                    #eprint(repr(info['config']))
                    info['config_fname_mtime'] = new_mtime
        except:
            eprint("xmms2-tail: unable to read config file")
            pass

        if 'playback_status' in info:
            info['playback_status_icon'] = info['config']['playback_status_icons'][playback_status_icon_name[info['playback_status']]]

        if name == 'playlist_current_pos':
            info['playlist_current_position'] = value["position"] + 1

        if 'playback_current_info' in info:
            if 'duration' in info['playback_current_info']:
                info['playback_current_info'][('unused', 'duration_formatted')] = format_timedelta(info['playback_current_info']['duration'])
            if 'tracknr' not in info['playback_current_info']:
                info['playback_current_info'][('unused', 'tracknr')] = '({})'.format(info['playlist_current_position'])

        if name == 'playlist_list_entries':
            info['playlist_num_entries'] = len(value)

        if name == 'playback_current_id':
            xc.medialib_get_info(value, cb = update_for('playback_current_info'))

        if name == 'playlist_current_pos':
            xc.playlist_list_entries(cb = update_for('playlist_list_entries'))

        if name == 'playlist_list_entries':
            xc.medialib_get_info(info['playlist_list_entries'][info['playlist_current_pos']["position"]], cb = update_for('playback_current_info'))

        #eprint(repr(info))
        #eprint()
        print(formatter.format(info['config']['line'], **info).encode('utf-8'))
        #eprint()
        sys.stdout.flush()

def update_for(name):
    return lambda r: update(name, r)

ml = gobject.MainLoop(None)

xc = xmmsclient.XMMS("xmms2-tail")
xc.connect()

conn = GLibConnector(xc)

xc.broadcast_playback_current_id(cb = update_for('playback_current_id'))
xc.broadcast_playback_status(cb = update_for('playback_status'))
xc.broadcast_playlist_current_pos(cb = update_for('playlist_current_pos'))
xc.broadcast_playlist_changed(cb = update_for('playlist_changed'))

xc.playback_current_id(cb = update_for('playback_current_id'))
xc.playlist_current_active(cb = update_for('playlist_current_active'))
xc.playlist_current_pos(cb = update_for('playlist_current_pos'))
xc.playback_status(cb = update_for('playback_status'))

ml.run()
